--- #YAML:1.0
name:               Text-SpellChecker
version:            0.04
abstract:           ~
author:
    - Brian Duggan <bduggan@matatu.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    MIME::Base64:  1
    Storable:      1
    Text::Aspell:  0.04
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
