--- #YAML:1.0
name:                Text-SpellChecker
version:             0.05
abstract:            ~
license:             perl
author:              
    - Brian Duggan <bduggan@matatu.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    MIME::Base64:                  1
    Storable:                      1
    Text::Aspell:                  0.04
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
