--- #YAML:1.0
name:               Text-SpellChecker
version:            0.11
abstract:           ~
author:
    - Brian Duggan <bduggan@matatu.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    MIME::Base64:    0
    Storable:        0
    Text::Hunspell:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
